[project]
name = "backend-of-my-project"
version = "0.1.0"
description = "pururururururu"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
    "djangorestframework>=3.16.1",
]
